-- 코드를 입력하세요
# SELECT * 
# FROM OFFLINE_SALE OS
# LEFT JOIN PRODUCT PR
# ON PR.PRODUCT_ID = OS.PRODUCT_ID
# ORDER BY PR.PRODUCT_ID

SELECT PR.PRODUCT_CODE, (PR.PRICE) * SUM(OS.SALES_AMOUNT) AS SALES
FROM OFFLINE_SALE OS
LEFT JOIN PRODUCT PR
ON PR.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY PR.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC