SELECT *
FROM (
    SELECT CAR.CAR_ID, CAR.CAR_TYPE, ROUND(CAR.DAILY_FEE * 30 * (1-PLAN.DISCOUNT_RATE /100)) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR CAR
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS 
        ON CAR.CAR_ID = HIS.CAR_ID AND (END_DATE >= '2022-11-01') #AND START_DATE <= '2022-11-30')
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN 
        ON CAR.CAR_TYPE = PLAN.CAR_TYPE AND DURATION_TYPE = '30일 이상'
    WHERE HIS.CAR_ID IS NULL 
    AND CAR.CAR_TYPE IN ('세단', 'SUV')
    ) A
WHERE FEE < 2000000 AND FEE >= 500000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC